# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-20 14:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20161107_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericCodeMapping',
            fields=[
                ('from_code', models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(b'^[\\w]*$', code=b'Invalid name', message=b'name must be alphanumeric')])),
                ('to_code', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(b'^[\\w]*$', code=b'Invalid name', message=b'name must be alphanumeric')])),
            ],
        ),
    ]
