# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-26 14:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_genericcodemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPQSaving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('bnf_code', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(b'^[\\w]*$', code=b'Invalid name', message=b'name must be alphanumeric')])),
                ('lowest_decile', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('price_per_dose', models.IntegerField()),
                ('possible_savings', models.FloatField()),
                ('formulation_swap', models.TextField(blank=True, null=True)),
                ('pct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.PCT')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Practice')),
            ],
        ),
    ]
