# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-02 13:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20170127_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppqsaving',
            name='bnf_code',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(b'^[\\w]*$', code=b'Invalid name', message=b'name must be alphanumeric')]),
        ),
    ]
