# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-08 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_presentation_is_current'),
        ('frontend', '0017_auto_20170202_1335'),
    ]

    operations = [
    ]
